apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: kasten-pvc
   namespace: kasten-io
spec:
   storageClassName: kasten
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 10Gi
