apiVersion: v1
kind: PersistentVolume
metadata:
   name: kasten-pv
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   storageClassName: kasten
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /
      server: 172.17.0.2
