apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nfs-pvc
   namespace: kasten-io
spec:
   storageClassName: kasten-nfs2
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 10Gi
