apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs-pv
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   storageClassName: kasten-nfs
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /home/nfs
      server: 172.17.19.47
