apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  AuthService
      name:  authentication
      auth_service: "auth-svc:8000"
      path_prefix: "/v0/authz"
      ambassador_id: [ "kasten.io/k10" ]
      allowed_request_headers:
      - "x-forwarded-access-token"
      ---
      apiVersion: getambassador.io/v3alpha1
      kind: Host
      name: ambassadorhost
      hostname: "*"
      ambassador_id: [ "kasten.io/k10" ]
      requestPolicy:
        insecure:
          action: Route
      ---
      apiVersion: getambassador.io/v3alpha1
      kind: Listener
      name: ambassadorlistener
      port: 8000
      securityModel: XFP
      protocol: HTTPS
      hostBinding:
        namespace:
          from: SELF
      ambassador_id: [ "kasten.io/k10" ]
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Module
      name:  ambassador
      config:
        service_port: 8000
      ambassador_id: [ "kasten.io/k10" ]
  name: gateway
  namespace: kasten-io
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    service: gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
